from __future__ import annotations

from typing import Any


def _source(
    source_name: str,
    source_type: str,
    *,
    is_free: bool = True,
    current_data_expected: bool = False,
    club_coverage: bool = False,
    international_coverage: bool = False,
    world_cup_coverage: bool = False,
    event_data_possible: bool = False,
    shot_xg_possible: bool = False,
    lineup_possible: bool = False,
    odds_possible: bool = False,
    strength_rating_possible: bool = False,
    style_proxy_possible: bool = False,
    historical_only: bool = False,
    requires_optional_dependency: str = "",
    requires_network: bool = False,
    reliability_notes: str = "",
    limitation_notes: str = "",
) -> dict[str, Any]:
    return {
        "source_name": source_name,
        "source_type": source_type,
        "is_free": is_free,
        "current_data_expected": current_data_expected,
        "club_coverage": club_coverage,
        "international_coverage": international_coverage,
        "world_cup_coverage": world_cup_coverage,
        "event_data_possible": event_data_possible,
        "shot_xg_possible": shot_xg_possible,
        "lineup_possible": lineup_possible,
        "odds_possible": odds_possible,
        "strength_rating_possible": strength_rating_possible,
        "style_proxy_possible": style_proxy_possible,
        "historical_only": historical_only,
        "requires_optional_dependency": requires_optional_dependency,
        "requires_network": requires_network,
        "reliability_notes": reliability_notes,
        "limitation_notes": limitation_notes,
    }


def get_source_registry() -> dict[str, dict[str, Any]]:
    return {
        "openfootball_worldcup": _source(
            "openfootball_worldcup",
            "historical_open_data",
            current_data_expected=True,
            international_coverage=True,
            world_cup_coverage=True,
            requires_network=True,
            reliability_notes="Candidate static/open fixture backbone for World Cup schedules and results.",
            limitation_notes="Fixture/schedule structure only. No xG, lineups, or event data.",
        ),
        "thestatsapi_worldcup": _source(
            "thestatsapi_worldcup",
            "api_like",
            current_data_expected=True,
            international_coverage=True,
            world_cup_coverage=True,
            requires_network=True,
            reliability_notes="Candidate free World Cup fixture JSON/CSV source.",
            limitation_notes="Fixture/schedule structure only unless fields are explicitly present.",
        ),
        "football_data": _source(
            "football_data",
            "csv",
            current_data_expected=True,
            club_coverage=True,
            odds_possible=True,
            style_proxy_possible=True,
            requires_network=False,
            reliability_notes="Stable CSV format when files are present locally; currentness depends on source refresh cadence.",
            limitation_notes="Match-level results, fixtures, basic stats, and odds only. No event/tracking data.",
        ),
        "soccerdata": _source(
            "soccerdata",
            "wrapper",
            current_data_expected=True,
            club_coverage=True,
            international_coverage=True,
            world_cup_coverage=True,
            event_data_possible=True,
            shot_xg_possible=True,
            lineup_possible=True,
            strength_rating_possible=True,
            style_proxy_possible=True,
            requires_optional_dependency="soccerdata",
            requires_network=True,
            reliability_notes="Useful wrapper ecosystem if installed; individual readers may break when upstream sites change.",
            limitation_notes="Optional dependency. Network probing is disabled by default.",
        ),
        "sofascore": _source(
            "sofascore",
            "api_like",
            current_data_expected=True,
            club_coverage=True,
            international_coverage=True,
            world_cup_coverage=True,
            event_data_possible=True,
            shot_xg_possible=True,
            lineup_possible=True,
            style_proxy_possible=True,
            requires_network=True,
            reliability_notes="Candidate for current fixtures, match stats, lineups, xG/xGOT where exposed.",
            limitation_notes="Unofficial access can change. Do not bypass anti-bot, login, CAPTCHA, or paywall controls.",
        ),
        "whoscored": _source(
            "whoscored",
            "scrape",
            current_data_expected=True,
            club_coverage=True,
            international_coverage=True,
            world_cup_coverage=True,
            event_data_possible=True,
            shot_xg_possible=False,
            lineup_possible=True,
            style_proxy_possible=True,
            requires_network=True,
            reliability_notes="Possible source for event/action style proxies.",
            limitation_notes="Likely fragile and may require browser automation later; no Selenium/browser driver requirement in Phase 21.",
        ),
        "fbref": _source(
            "fbref",
            "scrape",
            current_data_expected=True,
            club_coverage=True,
            international_coverage=True,
            world_cup_coverage=True,
            shot_xg_possible=True,
            lineup_possible=False,
            style_proxy_possible=True,
            requires_network=True,
            reliability_notes="Useful aggregate team/player tables when available.",
            limitation_notes="Table structure and rate limits can change; no fragile scraping in tests.",
        ),
        "understat": _source(
            "understat",
            "scrape",
            current_data_expected=True,
            club_coverage=True,
            international_coverage=False,
            world_cup_coverage=False,
            event_data_possible=True,
            shot_xg_possible=True,
            style_proxy_possible=True,
            requires_network=True,
            reliability_notes="Candidate for club xG and shot-level top-league data.",
            limitation_notes="Not a World Cup or broad international solution.",
        ),
        "clubelo": _source(
            "clubelo",
            "api_like",
            current_data_expected=True,
            club_coverage=True,
            strength_rating_possible=True,
            requires_network=True,
            reliability_notes="Candidate for club strength priors.",
            limitation_notes="Strength rating only; not a style/event source.",
        ),
        "eloratings": _source(
            "eloratings",
            "api_like",
            current_data_expected=True,
            international_coverage=True,
            world_cup_coverage=True,
            strength_rating_possible=True,
            requires_network=True,
            reliability_notes="Candidate for national-team and World Cup strength priors.",
            limitation_notes="Strength rating only; not a style/event source.",
        ),
        "espn_scoreboard": _source(
            "espn_scoreboard",
            "api_like",
            current_data_expected=True,
            international_coverage=True,
            world_cup_coverage=True,
            requires_network=True,
            reliability_notes="Free/keyless scoreboard fallback candidate for fixtures, scores, and results.",
            limitation_notes="Unofficial fallback. Not high trust and not an xG/style source.",
        ),
        "statsbomb_open_data": _source(
            "statsbomb_open_data",
            "historical_open_data",
            current_data_expected=False,
            club_coverage=True,
            international_coverage=True,
            world_cup_coverage=True,
            event_data_possible=True,
            shot_xg_possible=True,
            lineup_possible=True,
            style_proxy_possible=True,
            historical_only=True,
            requires_network=False,
            reliability_notes="Excellent historical validation/event-style fixture when local open data exists.",
            limitation_notes="Historical only for this project. Not a current-data source and not paid/current StatsBomb.",
        ),
    }
